driver : driver.o iofunctions.o iofunctions.h pokemon.h
	gcc -o driver driver.o iofunctions.o

driver.o : driver.c
	gcc -ansi -pedantic-errors -Wall -c driver.c

iofunctions.o : iofunctions.c
	gcc -ansi -pedantic-errors -Wall -c iofunctions.c
